---
name: Debian Base Image
version: 1.0.0
slug: debian-base
description: Docker Debian base images used by Home Assistant Community Add-ons.
url: https://github.com/kecajtop/hassio-addons/tree/master/git
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386