---
name: Git
version: 1.0.2
slug: ubuntu-base
description: Docker Ubuntu base images used by Home Assistant Community Add-ons Git server.
url: https://github.com/hassio-addons/addon-ubuntu-base
init: false
arch:
  - aarch64
  - amd64
  - armv7
